spring.application.name=neurocart
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/neurocart
spring.datasource.username=root
spring.datasource.password=namrata@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
